# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatservice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chatservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63hatservice.proto\x12\x04\x63hat\"3\n\rStreamRequest\x12\x10\n\x08playerId\x18\x01 \x01(\t\x12\x10\n\x08\x63hannels\x18\x02 \x03(\t\"Q\n\x0b\x43hatMessage\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x10\n\x08playerId\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"[\n\x0eWhisperRequest\x12\x14\n\x0c\x66romPlayerId\x18\x01 \x01(\t\x12\x12\n\ntoPlayerId\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"7\n\x14\x43reateChannelRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tcreatorId\x18\x02 \x01(\t\"%\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xde\x01\n\x0b\x43hatService\x12:\n\x0eStreamMessages\x12\x13.chat.StreamRequest\x1a\x11.chat.ChatMessage0\x01\x12+\n\x0bSendMessage\x12\x11.chat.ChatMessage\x1a\t.chat.Ack\x12\x36\n\rCreateChannel\x12\x1a.chat.CreateChannelRequest\x1a\t.chat.Ack\x12.\n\x0bSendWhisper\x12\x14.chat.WhisperRequest\x1a\t.chat.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQUEST']._serialized_start=27
  _globals['_STREAMREQUEST']._serialized_end=78
  _globals['_CHATMESSAGE']._serialized_start=80
  _globals['_CHATMESSAGE']._serialized_end=161
  _globals['_WHISPERREQUEST']._serialized_start=163
  _globals['_WHISPERREQUEST']._serialized_end=254
  _globals['_CREATECHANNELREQUEST']._serialized_start=256
  _globals['_CREATECHANNELREQUEST']._serialized_end=311
  _globals['_ACK']._serialized_start=313
  _globals['_ACK']._serialized_end=350
  _globals['_CHATSERVICE']._serialized_start=353
  _globals['_CHATSERVICE']._serialized_end=575
# @@protoc_insertion_point(module_scope)
