# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import npcservice_pb2 as npcservice__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in npcservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NPCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpawnNPc = channel.unary_unary(
                '/npc.NPCService/SpawnNPc',
                request_serializer=npcservice__pb2.NPCSpawnRequest.SerializeToString,
                response_deserializer=npcservice__pb2.NPCSpawnResponse.FromString,
                _registered_method=True)
        self.WalkNPC = channel.unary_unary(
                '/npc.NPCService/WalkNPC',
                request_serializer=npcservice__pb2.NPCWalkRequest.SerializeToString,
                response_deserializer=npcservice__pb2.NPCWalkResponse.FromString,
                _registered_method=True)
        self.DespawnNPC = channel.unary_unary(
                '/npc.NPCService/DespawnNPC',
                request_serializer=npcservice__pb2.NPCDeSpawnRequest.SerializeToString,
                response_deserializer=npcservice__pb2.NPCDespanwResponse.FromString,
                _registered_method=True)
        self.StreamNPcs = channel.unary_stream(
                '/npc.NPCService/StreamNPcs',
                request_serializer=npcservice__pb2.NPCStreamReqest.SerializeToString,
                response_deserializer=npcservice__pb2.NPCUpdate.FromString,
                _registered_method=True)


class NPCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SpawnNPc(self, request, context):
        """spawn a new NPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WalkNPC(self, request, context):
        """Move NPC - server decides next random walk step
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DespawnNPC(self, request, context):
        """Despawn a NPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamNPcs(self, request, context):
        """Stream all active NPC Updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpawnNPc': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnNPc,
                    request_deserializer=npcservice__pb2.NPCSpawnRequest.FromString,
                    response_serializer=npcservice__pb2.NPCSpawnResponse.SerializeToString,
            ),
            'WalkNPC': grpc.unary_unary_rpc_method_handler(
                    servicer.WalkNPC,
                    request_deserializer=npcservice__pb2.NPCWalkRequest.FromString,
                    response_serializer=npcservice__pb2.NPCWalkResponse.SerializeToString,
            ),
            'DespawnNPC': grpc.unary_unary_rpc_method_handler(
                    servicer.DespawnNPC,
                    request_deserializer=npcservice__pb2.NPCDeSpawnRequest.FromString,
                    response_serializer=npcservice__pb2.NPCDespanwResponse.SerializeToString,
            ),
            'StreamNPcs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamNPcs,
                    request_deserializer=npcservice__pb2.NPCStreamReqest.FromString,
                    response_serializer=npcservice__pb2.NPCUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'npc.NPCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('npc.NPCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NPCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SpawnNPc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/npc.NPCService/SpawnNPc',
            npcservice__pb2.NPCSpawnRequest.SerializeToString,
            npcservice__pb2.NPCSpawnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WalkNPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/npc.NPCService/WalkNPC',
            npcservice__pb2.NPCWalkRequest.SerializeToString,
            npcservice__pb2.NPCWalkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DespawnNPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/npc.NPCService/DespawnNPC',
            npcservice__pb2.NPCDeSpawnRequest.SerializeToString,
            npcservice__pb2.NPCDespanwResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamNPcs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/npc.NPCService/StreamNPcs',
            npcservice__pb2.NPCStreamReqest.SerializeToString,
            npcservice__pb2.NPCUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
